blank_issues_enabled: false
contact_links:
  - name: User Support Forum Thread
    url: https://gbatemp.net/threads/wiiflow-lite.422685/
    about: Please ask questions about how to setup or use WiiFlow Lite here
